[package]
name = "bson_object_id"
version = "0.1.0"
edition = "2021"
authors = ["Nick Spain <nicholas.spain@stileeducation.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
